discovery_adventure/urls.py
from django.contrib import admin
from django.urls import path, include
from discovery_adventure import settings
from discovery_adventure.context_processors import search_results

from viewer import views
from accounts.views import SignUpView, my_view, ProfileUpdateView, CustomPasswordChangeView

from viewer.views import home, ProductsListView, ProductTemplateView, ProductCreateView, CategoryListView, \
    CategoryTemplateView, RandomProductTemplateView, FAQView, \
    ProductUpdateView, ProductDeleteView, ProductSortedLowListView, ProductSortedHighListView, \
    add_to_cart, cart_view, delete_order_line, remove_from_cart, Contactview, checkout_view, place_order, \
    CategoryCreateView, order_confirmation, product_select_view

urlpatterns = [

    path('hello/', views.hello, name='hello'),

    path('', CategoryListView.as_view(), name='home'), # "domovská stránka", která zobrazuje kategorie

    path('shop/', ProductsListView.as_view(), name='shop'), # zobrazení všech produktů
    path('category/create/', CategoryCreateView.as_view(), name='category_create'), # vytvoření kategorie
    path('category/<pk>/', CategoryTemplateView.as_view(), name='category'), # zobrazení produktů dané kategorie
    path('shop/random/', RandomProductTemplateView.as_view(), name='random'),
    path('shop/<pk>/', ProductTemplateView.as_view(), name='detail'), # zobrazení detailu produktu
    path('shop-nejdrazsi/', ProductSortedLowListView.as_view(), name='shop-nejdrazsi'), #zobrazi vsechny produkty serazene od nejlevnejsiho
    path('shop-nejlevnejsi/', ProductSortedHighListView.as_view(), name='shop-nejlevnejsi'), #zobrazi vsechny produkty serazene od nejdrazsiho
    path('products/select/', product_select_view, name='product_select'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'), # vytvoření produktu
    path('product/update/<pk>/', ProductUpdateView.as_view(), name='product_update'), # update produktu
    path('product/delete/<pk>/', ProductDeleteView.as_view(), name='product_delete'), # odstranění produktu
    path('search/', views.search_view, name='search_results'),

    path('faq/', FAQView.as_view(), name='faq'), # faq stránka
    path('contact/', Contactview.as_view(), name='contact'), # kontakt stránka

    path('add-to-cart/<pk>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove_from_cart'),
    path('delete-order-line/<pk>/', delete_order_line, name='delete_order_line'),
    path('cart/', cart_view, name='cart_view'),
    path('checkout/', checkout_view, name='checkout'),
    path('place_order/<pk>/', place_order, name='place_order'),
    path('order_confirmation/', order_confirmation, name='order_confirmation'),


    path('accounts/login/', my_view, name='login'),  # vlastní view pro login
    path('accounts/signup/', SignUpView.as_view(), name='signup'),          # vlastní view pro signup
    path('accounts/password_change/', CustomPasswordChangeView.as_view(), name='password_change'), # view pro změnu hesla
    path('accounts/info_change/', ProfileUpdateView.as_view(), name='profile_update'), # view pro změnu údajů
    path('accounts/', include('django.contrib.auth.urls')), # default django view

    path('admin/', admin.site.urls),

]

viewer/models.py
from datetime import date

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import *  #(Model, CharField, ForeignKey, DO_NOTHING,
from django.core.validators import MinValueValidator
from django.urls import reverse

from accounts.models import Profile


class Manufacturer(Model):
    name = CharField(max_length=80, null=True, blank=False)

    class Meta:
        ordering = ['name']

    def __repr__(self):
        return f"<Manufacturer: {self.name}>"

    def __str__(self):
        return f"{self.name}"


class Category(models.Model):
    name = models.CharField(max_length=42, null=True, blank=False)
    thumbnail = models.CharField(max_length=200, blank=True, null=True)  # Cesta k obrázku

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def clean(self):
        if len(self.name) < 2:
            raise ValidationError("Name must be at least 2 characters")


class Product(models.Model):
    class ProductType(models.TextChoices):
        SHOES = 'BT', 'Boty'
        CLOTHES = 'OB', 'Oblečení'
        ACCESSORIES = 'ACS', 'Příslušenství'
        OTHER = 'OT', 'Jiné'

    title = models.CharField(max_length=100, null=True, blank=False)
    product_type = models.CharField(
        max_length=3,
        choices=ProductType.choices,
        default=ProductType.OTHER,
    )
    description = models.CharField(max_length=500, null=True, blank=False)
    thumbnail = models.CharField(max_length=200, blank=True, null=True)  # Cesta k obrázku
    price = models.IntegerField(default=0, null=True, blank=False, validators=[MinValueValidator(1)])
    stock = models.IntegerField(default=0, null=True, blank=False, validators=[MinValueValidator(0)])
    manufacturer = models.ForeignKey('Manufacturer', on_delete=models.DO_NOTHING, null=True, blank=False)
    categories = models.ManyToManyField('Category', related_name='products', blank=True)

    class Meta:
        ordering = ['title', 'stock', 'price']

    def __str__(self):
        return f"{self.title}, in stock: {self.stock}, price: {self.price} EUR"

    def __repr__(self):
        return f"<Product: {self.title}, in stock: {self.stock}, price: {self.price} EUR>"

    def add_to_cart_url(self):
        return reverse("add_to_cart", kwargs=
        {"pk": self.pk
         })

    def clean(self):
        if self.price <= 0:
            raise ValidationError('Price must be greater than 0.')
        if self.stock < 0:
            raise ValidationError('Stock cannot be negative.')


class Cart(Model):
    quantity = IntegerField(default=0, null=True, blank=False)
    Product = ManyToManyField(Product, related_name='cart')


class Order(Model):
    total_cost = IntegerField(default=0, null=True, blank=False)
    delivery_address = CharField(max_length=100, null=True, blank=False)
    date_of_sale = DateField(null=True, blank=False)
    status = CharField(max_length=42, null=True, blank=False)
    User = ForeignKey(Profile, on_delete=DO_NOTHING, null=True, blank=False)

    def clean(self):
        if self.total_cost < 0:
            raise ValidationError('Total cost cannot be negative.')


class Order_Line(Model):
    product_price = IntegerField(default=0, null=True, blank=False)
    quantity = IntegerField(default=1, null=True, blank=False)
    Product = ForeignKey(Product, on_delete=DO_NOTHING, null=True, blank=False)
    Order = ForeignKey(Order, on_delete=DO_NOTHING, null=True, blank=False)

    def total_order_line_price(self):
        return self.product_price * self.quantity

    total_order_line_price.short_description = 'Total Price'


class Payment(Model):
    Order = ForeignKey(Order, on_delete=DO_NOTHING, null=True, blank=False)
    date_of_payment = DateTimeField(null=True, blank=False)

viewer/views.py
import random
from concurrent.futures._base import LOGGER

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.db.models.functions import datetime
from django.http import HttpResponse, request
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import TemplateView, ListView, FormView, CreateView, UpdateView, DeleteView, DetailView
from django_addanother.views import CreatePopupMixin
from django_addanother.widgets import AddAnotherWidgetWrapper
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q

from accounts.views import ProfileUpdateForm
from viewer.models import *

from django.forms import *


# Funkce pro zobrazení úvodní stránky
def home(request):
    return render(request, "home.html")


# Pohled pro FAQ stránku
class FAQView(TemplateView):
    template_name = "faq.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()  # Získání všech kategorií
        context['current_template'] = "FAQ"  # Nastavení aktuální šablony
        try:
            context['user_city'] = self.request.user.profile.city
        except:
            context['user_city'] = 'Praha'
        return context


# Funkce pro zobrazení uvítací stránky
def hello(request):
    return render(request, "hello.html")


# Pohled pro kontaktní stránku
class Contactview(TemplateView):
    template_name = "contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()  # Získání všech kategorií
        context['current_template'] = "kONTAKT"  # Nastavení aktuální šablony
        try:
            context['user_city'] = self.request.user.profile.city
        except:
            context['user_city'] = 'Praha'
        return context


# Pohled pro zobrazení seznamu kategorií
class CategoryListView(ListView):
    model = Category
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()  # Získání všech kategorií
        for category in categories:
            # Spočítání počtu produktů v každé kategorii
            category.product_count = Product.objects.filter(categories=category).count()
        context['categories'] = categories
        context['current_template'] = "Kategorie"  # Nastavení aktuální šablony
        try:
            context['user_city'] = self.request.user.profile.city
        except:
            context['user_city'] = 'Praha'

        return context


# Pohled pro zobrazení produktů v konkrétní kategorii
class CategoryTemplateView(TemplateView):
    template_name = "products_by_category.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']  # Získání ID kategorie z URL
        category = get_object_or_404(Category, pk=pk)  # Získání kategorie nebo 404 pokud neexistuje

        # Získání produktů v kategorii
        products = Product.objects.filter(categories=category)

        # Paginace produktů po 9 na stránku
        paginator = Paginator(products, 9)
        page_number = self.request.GET.get('page', 1)  # Získání čísla stránky z GET parametru

        try:
            page_obj = paginator.get_page(page_number)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)  # Pokud je číslo stránky větší než počet stránek

        context["category"] = category
        context['page_obj'] = page_obj
        context['categories'] = Category.objects.all()

        # Nastavení počtu produktů v každé kategorii
        for cat in context['categories']:
            cat.product_count = Product.objects.filter(categories=cat).count()

        # Nastavení města uživatele
        user = self.request.user
        if hasattr(user, 'profile'):
            context['user_city'] = user.profile.city
        else:
            context['user_city'] = 'Praha'

        return context


# Pohled pro zobrazení všech produktů
class ProductsListView(ListView):
    model = Product
    template_name = 'shop.html'
    context_object_name = 'products'
    paginate_by = 12  # Paginace produktů po 12 na stránku

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()  # Získání všech kategorií
        context['current_template'] = "Všechny produkty"  # Nastavení aktuální šablony
        try:
            context['user_city'] = self.request.user.profile.city
        except:
            context['user_city'] = 'Praha'
        return context


# Pohled pro zobrazení produktů seřazených od nejlevnějšího
class ProductSortedHighListView(ListView):
    model = Product
    template_name = 'shop.html'
    context_object_name = 'products'
    paginate_by = 12

    def get_queryset(self):
        return Product.objects.all().order_by('price')  # Použijeme all() pro získání všech atributů a seřadíme vzestupně

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['current_template'] = "produkty seřazené od nejlevnějšího"
        try:
            context['user_city'] = self.request.user.profile.city
        except:
            context['user_city'] = 'Praha'
        return context


# Pohled pro zobrazení produktů seřazených od nejdražšího
class ProductSortedLowListView(ListView):
    model = Product
    template_name = 'shop.html'
    context_object_name = 'products'
    paginate_by = 12

    def get_queryset(self):
        return Product.objects.all().order_by('-price')  # Použijeme all() pro získání všech atributů

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['current_template'] = "produkty seřazené od nejdražšího"
        try:
            context['user_city'] = self.request.user.profile.city
        except:
            context['user_city'] = 'Praha'
        return context


# Pohled pro zobrazení nejnovějších produktů
class ProductNewestListView(ListView):
    model = Product
    template_name = 'shop.html'
    context_object_name = 'products'
    paginate_by = 12  # Paginace produktů po 3 na stránku

    def get_queryset(self):
        return Product.objects.order_by('-created_at')  # Seřazení produktů podle data vytvoření (novější první)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['current_template'] = "produkty seřazené od nejnovějšího"
        try:
            context['user_city'] = self.request.user.profile.city
        except:
            context['user_city'] = 'Praha'
        return context


# Pohled pro zobrazení detailu konkrétního produktu
class ProductTemplateView(TemplateView):
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']  # Získání ID produktu z URL
        product_ = Product.objects.get(id=pk)  # Získání produktu podle ID
        conversion_rate = 25.5  # Převodní kurz pro cenu (CZK na EUR)
        context["product"] = product_
        context["title"] = product_.title
        context["description"] = product_.description
        context["price"] = product_.price
        context["manufacturer"] = product_.manufacturer
        context["conversion_rate"] = conversion_rate
        context["price_czk"] = product_.price * conversion_rate  # Přepočet ceny na CZK
        context['categories'] = Category.objects.all()  # Získání všech kategorií
        context['current_template'] = "detail produktu"  # Nastavení aktuální šablony
        try:
            context['user_city'] = self.request.user.profile.city
        except:
            context['user_city'] = 'Praha'
        return context
        # context["reviews"] = Review.objects.filter(product=product_)
        # context["form_review"] = ReviewModelForm


# Pohled pro zobrazení náhodného produktu
class RandomProductTemplateView(TemplateView):
    template_name = 'random_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_count = Product.objects.count()  # Získání počtu produktů
        if product_count > 0:
            while True:
                random_index = random.randint(0, product_count - 1)  # Generování náhodného indexu produktu
                if Product.objects.filter(id=random_index).exists():  # Kontrola existence produktu s tímto ID
                    random_product = Product.objects.get(pk=random_index)
                    break
        else:
            random_product = None

        if random_product:
            conversion_rate = 25.5  # Převodní kurz pro cenu (CZK na EUR)
            context["product"] = random_product
            context["title"] = random_product.title
            context["description"] = random_product.description
            context["price"] = random_product.price
            context["manufacturer"] = random_product.manufacturer
            context["conversion_rate"] = conversion_rate
            context["price_czk"] = random_product.price * conversion_rate  # Přepočet ceny na CZK

        context['categories'] = Category.objects.all()  # Získání všech kategorií
        context['current_template'] = "Náhodný produkt"  # Nastavení aktuální šablony
        try:

viewer/templates/category_create.html
{% extends "form.html" %}
{% load static %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input id="id_submit" type="submit" value="Submit" class="btn btn-primary">
</form>

{% endblock %}

viewer/templates/contact.html
{% extends "base.html" %}
{% block content %}
<!-- Hlavní kontejner pro obsah stránky -->
<div class="container">
    <!-- Jumbotron - velký blok pro zvýraznění obsahu -->
    <div class="jumbotron">
        <!-- Kontejner pro FAQ (často kladené dotazy) -->
        <div class="faq-container">
            <!-- Sekce pro informace o obchodě -->
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <!-- Odkaz na domovskou stránku -->
                <a href="{% url 'home' %}" class="text-decoration-none">
                    <!-- Hlavní nadpis s názvem obchodu -->
                    <h1 class="m-0 display-9 font-weight-semi-bold">
                        <!-- Název obchodu s částí textu v jiném stylu -->
                        <span class="text-primary font-weight-light border px-1 mr-2">DA</span>Discovery adventure
                    </h1>
                </a>
                <!-- Popis obchodu -->
                <p>Náš obchod nabízí široký sortiment sportovního vybavení pro všechny věkové kategorie a úrovně dovedností. Od tenisek po fitness náčiní, máme vše pro vaše sportovní potřeby a zdravý životní styl.</p>
                <!-- Adresa obchodu -->
                <p class="mb-2">
                    <i class="fa fa-map-marker-alt text-primary mr-3"></i> Pražská ulice 123 <br> 110 00 Praha 1 <br> Česká republika
                </p>
                <!-- E-mailová adresa -->
                <p class="mb-2">
                    <i class="fa fa-envelope text-primary mr-3"></i>info@DA.cz
                </p>
                <!-- Telefonní číslo -->
                <p class="mb-0">
                    <i class="fa fa-phone-alt text-primary mr-3"></i>+420 730 525 754
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

viewer/templates/form.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Formulář pro odeslání dat metodou POST -->
<form method="POST">
    <!-- Token pro ochranu proti CSRF (Cross-Site Request Forgery) útokům -->
    {% csrf_token %}

    <!-- Vykreslení formuláře jako tabulky. Tento zápis zobrazí všechny formové prvky v tabulce. -->
    <table>{{ form }}</table>
    <input id="id_submit" type="submit" value="Uložit" class="btn btn-primary">
</form>

{% endblock %}

viewer/templates/hello.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% endblock %}

viewer/templates/login.html
{% extends "form.html" %}

viewer/templates/order_confirmation.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="alert alert-success mt-4">
        Objednávka byla úspěšně vytvořena! Děkujeme! Nyní již potřebujeme jen vytvořit s.r.o., nakoupit stovky produktů, napojit skladový systém na databázi a zprovoznit tisíc dalších funkcí!
    </div>
</div>
{% endblock %}

viewer/templates/products_by_category.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- Shop Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <!-- Shop Product Start -->
        <div class="col-lg-12 col-md-12">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <!-- Formulář pro vyhledávání produktů podle názvu -->
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Hledat dle názvu">
                                <div class="input-group-append">
                                    <span class="input-group-text bg-transparent text-primary">
                                        <i class="fa fa-search"></i>
                                    </span>
                                </div>
                            </div>
                        </form>

                        <!-- Tlačítko pro vytvoření nového produktu, zobrazí se jen pokud má uživatel oprávnění -->
                        {% if perms.accounts.add_product %}
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-md-4 text-center mb-1">
                                    <h5>
                                        <a href="{% url 'product_create' %}"
                                           class="btn btn-danger font-weight-bold text-monospace text-uppercase mb-1">
                                            Vytvořit nový produkt
                                        </a>
                                    </h5>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                        <!-- Dropdown menu pro řazení produktů -->
                        <div class="dropdown ml-4">
                            <button class="btn border dropdown-toggle" type="button" id="triggerId"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Seřadit dle
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                                <a class="dropdown-item" href="{% url 'shop-nejdrazsi' %}">Cena - nejdražší</a>
                                <a class="dropdown-item" href="{% url 'shop-nejlevnejsi' %}">Cena - nejlevnější</a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Cyklus pro zobrazení jednotlivých produktů -->
                {% for product in page_obj.object_list %}
                <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                    <div class="card product-item border-0 mb-4">
                        <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <!-- Odkaz na detail produktu -->
                            <a href="{% url 'detail' product.id %}" class="text-decoration-none">
                                {% if product.thumbnail %}
                                <img src="{% static 'img/'|add:product.thumbnail %}" alt="{{ product.name }}"
                                     class="img-fluid w-100">
                                {% endif %}
                            </a>
                        </div>
                        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                            <h6 class="text-truncate mb-3">{{ product.title }}</h6>
                            <div class="d-flex justify-content-center">
                                <h6>€ {{ product.price }}</h6>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between bg-light border">
                            <a href="{% url 'detail' product.id %}" class="btn btn-sm text-dark p-0"><i
                                    class="fas fa-eye text-primary mr-1"></i>Detail</a>
                            <a href="{{ product.add_to_cart_url }}" class="btn btn-sm text-dark p-0"><i
                                    class="fas fa-shopping-cart text-primary mr-1"></i>Do košíku</a>
                            {% if perms.accounts.change_product %}
                            <a href="{% url 'product_update' product.id %}"
                               class="btn btn-sm text-uppercase text-danger p-0"><i
                                    class="fas fa-edit text-primary mr-1"></i>Upravit</a>
                            {% endif %}
                            {% if perms.accounts.delete_product %}
                            <!-- Odkaz pro smazání produktu, zobrazí se jen pokud má uživatel oprávnění -->
                            <a href="{% url 'product_delete' product.id %}"
                               class="btn btn-sm text-uppercase text-danger p-0"><i
                                    class="fas fa-trash-alt text-primary mr-1"></i>Smazat</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}

                <!-- Paginace pro stránkování produktů -->
                <div class="col-12 pb-1">
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center mb-3">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            {% endif %}
                            {% for num in page_obj.paginator.page_range %}
                            <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->
{% endblock %}

viewer/templates/search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        {% if search_query %}
            <h2 class="section-title px-5"><span class="px-2">Výsledky vyhledávání pro "{{ search_query }}"</span></h2>
        {% else %}
            <h2 class="section-title px-5"><span class="px-2">Všechny produkty</span></h2>
        {% endif %}
    </div>
    <div class="row px-xl-5 pb-3">
        {% if search_products %}
            {% for object in search_products %}
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <div class="card product-item border-0 mb-4">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <!-- Odkaz na detail produktu -->
                        <a href="{% url 'detail' object.id %}" class="text-decoration-none">
                            {% if object.thumbnail %}
                            <img src="{% static 'img/'|add:object.thumbnail %}" alt="{{ object.name }}"
                                 class="img-fluid w-100">
                            {% endif %}
                        </a>
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">{{ object.title }}</h6>
                        <div class="d-flex justify-content-center">
                            <h6>€ {{ object.price }}</h6>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="{{ object.id }}" class="btn btn-sm text-dark p-0"><i
                                class="fas fa-eye text-primary mr-1"></i>Detail</a>
                        <a href="{{ object.add_to_cart_url }}" class="btn btn-sm text-dark p-0"><i
                                class="fas fa-shopping-cart text-primary mr-1"></i>Do košíku</a>
                        {% if perms.accounts.change_product %}
                        <a href="{% url 'product_update' object.id %}"
                           class="btn btn-sm text-uppercase text-danger p-0"><i
                                class="fas fa-edit text-primary mr-1"></i>Upravit</a>
                        {% endif %}
                        {% if perms.accounts.delete_product %}
                        <!-- Odkaz pro smazání produktu, zobrazí se jen pokud má uživatel oprávnění -->
                        <a href="{% url 'product_delete' object.id %}"
                           class="btn btn-sm text-uppercase text-danger p-0"><i
                                class="fas fa-trash-alt text-primary mr-1"></i>Smazat</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="col-12 text-center">
                {% if search_query %}
                    <p>Pro vyhledávaný výraz "{{ search_query }}" nebyly nalezeny žádné produkty.</p>
                {% else %}
                    <p>Zadejte hledaný výraz pro vyhledání produktů.</p>
                {% endif %}
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}